/**
 * Comprehensive branching scenario data for PathPilot simulations.
 * Each career has 10-20 scenario events with branching decision trees and persistent consequences.
 */

export const BRANCHING_SCENARIOS = {
  software_engineer: {
    startingScenarioKey: "se_intro",
    metrics: [
      { name: "Product Quality", initialValue: 50 },
      { name: "Technical Debt", initialValue: 30 },
      { name: "Team Morale", initialValue: 60 },
      { name: "Deadline Progress", initialValue: 50 },
      { name: "User Satisfaction", initialValue: 55 },
    ],
    scenarios: [
      {
        scenarioKey: "se_intro",
        title: "Welcome to TechCorp",
        description: "You've just joined TechCorp as a junior software engineer. Your first day is here. The lead engineer, Sarah, greets you and explains that your team is working on a critical feature for the company's main product, which is used by millions of users.",
        stageNumber: 1,
        choices: [
          {
            id: "se_intro_a",
            text: "Ask Sarah about the current codebase and architecture",
            nextScenarioKey: "se_codebase",
            metricsImpact: { "Product Quality": 5, "Technical Debt": -5 },
            consequence: "Sarah appreciates your initiative and gives you a thorough overview.",
          },
          {
            id: "se_intro_b",
            text: "Jump into the first task without asking questions",
            nextScenarioKey: "se_first_bug",
            metricsImpact: { "Deadline Progress": 10, "Product Quality": -10 },
            consequence: "You start working quickly, but you miss important context.",
          },
        ],
      },
      {
        scenarioKey: "se_codebase",
        title: "Understanding the System",
        description: "Sarah walks you through the codebase. You notice that while the core logic is solid, there are many shortcuts and quick fixes scattered throughout. She mentions that the team has been under pressure to deliver features quickly.",
        stageNumber: 2,
        choices: [
          {
            id: "se_codebase_a",
            text: "Suggest a refactoring plan to clean up the technical debt",
            nextScenarioKey: "se_refactor_proposal",
            metricsImpact: { "Technical Debt": -15, "Deadline Progress": -10 },
            consequence: "Your suggestion is noted, but the team is focused on features right now.",
          },
          {
            id: "se_codebase_b",
            text: "Focus on learning the existing patterns and start contributing features",
            nextScenarioKey: "se_first_feature",
            metricsImpact: { "Deadline Progress": 15, "Team Morale": 10 },
            consequence: "You quickly become productive and the team appreciates your contributions.",
          },
        ],
      },
      {
        scenarioKey: "se_first_bug",
        title: "Your First Bug",
        description: "You're assigned a bug in the user authentication system. It's a critical issue affecting 5% of users. You start investigating but realize you don't fully understand the system architecture.",
        stageNumber: 2,
        choices: [
          {
            id: "se_first_bug_a",
            text: "Ask for help from a senior engineer",
            nextScenarioKey: "se_mentorship",
            metricsImpact: { "Team Morale": 10, "Product Quality": 20 },
            consequence: "A senior engineer helps you fix the bug and teaches you valuable lessons.",
          },
          {
            id: "se_first_bug_b",
            text: "Try to fix it yourself by trial and error",
            nextScenarioKey: "se_wrong_fix",
            metricsImpact: { "Product Quality": -20, "User Satisfaction": -15 },
            consequence: "Your fix introduces new bugs, making the situation worse.",
          },
        ],
      },
      {
        scenarioKey: "se_refactor_proposal",
        title: "Refactoring Pushback",
        description: "You propose a refactoring plan to address technical debt. The engineering manager listens but says the company's priority is shipping new features to meet investor expectations. However, she acknowledges the problem.",
        stageNumber: 3,
        choices: [
          {
            id: "se_refactor_proposal_a",
            text: "Accept the decision and focus on features",
            nextScenarioKey: "se_feature_sprint",
            metricsImpact: { "Deadline Progress": 20, "Technical Debt": 10 },
            consequence: "You become a productive team member, but technical debt continues to accumulate.",
          },
          {
            id: "se_refactor_proposal_b",
            text: "Propose a compromise: refactor while building features",
            nextScenarioKey: "se_incremental_refactor",
            metricsImpact: { "Technical Debt": -10, "Deadline Progress": 5 },
            consequence: "The manager is impressed by your pragmatism and agrees to a hybrid approach.",
          },
        ],
      },
      {
        scenarioKey: "se_first_feature",
        title: "Building Your First Feature",
        description: "You're assigned to build a new dashboard feature. The requirements are clear, and you have two weeks to complete it. Your team is supportive and available for questions.",
        stageNumber: 3,
        choices: [
          {
            id: "se_first_feature_a",
            text: "Build it quickly using existing patterns, even if not perfect",
            nextScenarioKey: "se_quick_delivery",
            metricsImpact: { "Deadline Progress": 25, "Product Quality": -5 },
            consequence: "You deliver on time, and the feature works well enough for users.",
          },
          {
            id: "se_first_feature_b",
            text: "Take time to build it well, with proper testing and documentation",
            nextScenarioKey: "se_quality_delivery",
            metricsImpact: { "Product Quality": 20, "Deadline Progress": -5 },
            consequence: "You deliver slightly late, but the feature is robust and well-documented.",
          },
        ],
      },
      {
        scenarioKey: "se_mentorship",
        title: "Learning from Experience",
        description: "Your mentor, David, helps you fix the authentication bug and explains the underlying architecture. He also invites you to code review sessions and technical discussions.",
        stageNumber: 3,
        choices: [
          {
            id: "se_mentorship_a",
            text: "Actively participate in code reviews and ask lots of questions",
            nextScenarioKey: "se_growth_path",
            metricsImpact: { "Product Quality": 15, "Team Morale": 15 },
            consequence: "You rapidly improve your skills and become a valued team member.",
          },
          {
            id: "se_mentorship_b",
            text: "Thank David but prefer to work independently",
            nextScenarioKey: "se_independent_path",
            metricsImpact: { "Deadline Progress": 10, "Product Quality": 5 },
            consequence: "You make progress, but miss out on deeper learning opportunities.",
          },
        ],
      },
      {
        scenarioKey: "se_wrong_fix",
        title: "Consequences of Rushing",
        description: "Your attempted fix causes a cascading failure. The authentication system is now down for 20% of users. The team is in crisis mode, and the manager is frustrated.",
        stageNumber: 3,
        choices: [
          {
            id: "se_wrong_fix_a",
            text: "Own the mistake, apologize, and work with the team to fix it",
            nextScenarioKey: "se_recovery",
            metricsImpact: { "Team Morale": -10, "Product Quality": -30 },
            consequence: "The team appreciates your honesty, but trust is damaged.",
          },
          {
            id: "se_wrong_fix_b",
            text: "Blame the unclear requirements and avoid responsibility",
            nextScenarioKey: "se_blame_game",
            metricsImpact: { "Team Morale": -30, "Product Quality": -40 },
            consequence: "The team loses confidence in you, and your reputation suffers.",
          },
        ],
      },
      {
        scenarioKey: "se_feature_sprint",
        title: "The Feature Sprint",
        description: "Your team enters a high-intensity sprint to deliver three major features. You're working 50+ hour weeks, and the pressure is mounting. Some team members are showing signs of burnout.",
        stageNumber: 4,
        choices: [
          {
            id: "se_feature_sprint_a",
            text: "Push through and deliver all features on time",
            nextScenarioKey: "se_sprint_success",
            metricsImpact: { "Deadline Progress": 30, "Team Morale": -20 },
            consequence: "You meet the deadline, but team morale takes a hit.",
          },
          {
            id: "se_feature_sprint_b",
            text: "Suggest a more sustainable pace and realistic timeline",
            nextScenarioKey: "se_sustainable_pace",
            metricsImpact: { "Team Morale": 15, "Deadline Progress": -10 },
            consequence: "The manager appreciates your perspective, and the team's well-being improves.",
          },
        ],
      },
      {
        scenarioKey: "se_incremental_refactor",
        title: "Refactoring While Shipping",
        description: "You start a hybrid approach: refactoring one module while building a new feature in another. It's challenging to balance both, but the team is supportive.",
        stageNumber: 4,
        choices: [
          {
            id: "se_incremental_refactor_a",
            text: "Prioritize the refactoring to reduce future technical debt",
            nextScenarioKey: "se_debt_reduction",
            metricsImpact: { "Technical Debt": -20, "Product Quality": 10 },
            consequence: "You make significant progress on technical debt.",
          },
          {
            id: "se_incremental_refactor_b",
            text: "Prioritize the feature to meet business deadlines",
            nextScenarioKey: "se_feature_priority",
            metricsImpact: { "Deadline Progress": 20, "Technical Debt": -5 },
            consequence: "The feature ships on time, and some technical debt is addressed.",
          },
        ],
      },
      {
        scenarioKey: "se_quick_delivery",
        title: "Success and Feedback",
        description: "Your dashboard feature launches successfully. Users love it, and it gets positive feedback. However, you notice some performance issues under heavy load.",
        stageNumber: 4,
        choices: [
          {
            id: "se_quick_delivery_a",
            text: "Immediately start optimizing the performance",
            nextScenarioKey: "se_optimization",
            metricsImpact: { "Product Quality": 15, "User Satisfaction": 10 },
            consequence: "You fix the performance issues and user satisfaction increases.",
          },
          {
            id: "se_quick_delivery_b",
            text: "Move on to the next feature and address performance later",
            nextScenarioKey: "se_accumulation",
            metricsImpact: { "Deadline Progress": 15, "Product Quality": -10 },
            consequence: "You stay productive, but performance issues accumulate.",
          },
        ],
      },
      {
        scenarioKey: "se_quality_delivery",
        title: "Quality Pays Off",
        description: "Your well-built dashboard feature launches with minimal bugs. The code review is smooth, and your documentation helps other team members understand the system.",
        stageNumber: 4,
        choices: [
          {
            id: "se_quality_delivery_a",
            text: "Continue prioritizing quality in all future work",
            nextScenarioKey: "se_quality_culture",
            metricsImpact: { "Product Quality": 20, "Team Morale": 10 },
            consequence: "You become known as a quality-focused engineer.",
          },
          {
            id: "se_quality_delivery_b",
            text: "Try to balance quality with speed for future features",
            nextScenarioKey: "se_balanced_approach",
            metricsImpact: { "Product Quality": 10, "Deadline Progress": 10 },
            consequence: "You find a sustainable middle ground.",
          },
        ],
      },
      {
        scenarioKey: "se_growth_path",
        title: "Rapid Growth",
        description: "After three months of active learning, you're now leading code reviews and mentoring new junior engineers. Your technical skills have grown significantly.",
        stageNumber: 5,
        choices: [
          {
            id: "se_growth_path_a",
            text: "Pursue a senior engineer promotion",
            nextScenarioKey: "se_senior_role",
            metricsImpact: { "Product Quality": 15, "Team Morale": 20 },
            consequence: "You're promoted to senior engineer and lead a small team.",
          },
          {
            id: "se_growth_path_b",
            text: "Explore a specialized technical track (e.g., architecture)",
            nextScenarioKey: "se_specialist_path",
            metricsImpact: { "Product Quality": 25, "Technical Debt": -15 },
            consequence: "You become the go-to expert for system architecture.",
          },
        ],
      },
      {
        scenarioKey: "se_independent_path",
        title: "Solo Contributor",
        description: "You continue working independently, delivering features on time. However, you notice you're not growing as quickly as your peers who actively seek mentorship.",
        stageNumber: 5,
        choices: [
          {
            id: "se_independent_path_a",
            text: "Reconsider and reach out to David for mentorship",
            nextScenarioKey: "se_late_mentorship",
            metricsImpact: { "Product Quality": 10, "Team Morale": 15 },
            consequence: "It's never too late to seek guidance and grow.",
          },
          {
            id: "se_independent_path_b",
            text: "Continue your independent path and focus on shipping",
            nextScenarioKey: "se_plateau",
            metricsImpact: { "Deadline Progress": 10, "Product Quality": 5 },
            consequence: "You remain productive but plateau in your growth.",
          },
        ],
      },
      {
        scenarioKey: "se_recovery",
        title: "Rebuilding Trust",
        description: "After the authentication failure, you work overtime with the team to fix the issue and implement safeguards. Your willingness to take responsibility helps rebuild trust.",
        stageNumber: 4,
        choices: [
          {
            id: "se_recovery_a",
            text: "Propose implementing better testing and code review processes",
            nextScenarioKey: "se_process_improvement",
            metricsImpact: { "Product Quality": 20, "Team Morale": 10 },
            consequence: "You help prevent similar issues in the future.",
          },
          {
            id: "se_recovery_b",
            text: "Focus on being more careful in your work going forward",
            nextScenarioKey: "se_cautious_approach",
            metricsImpact: { "Product Quality": 10, "Team Morale": 5 },
            consequence: "You become more careful, but the team remains cautious around you.",
          },
        ],
      },
      {
        scenarioKey: "se_blame_game",
        title: "Damaged Reputation",
        description: "The team is frustrated with your response to the failure. Your manager has a difficult conversation with you about accountability and teamwork.",
        stageNumber: 4,
        choices: [
          {
            id: "se_blame_game_a",
            text: "Acknowledge your mistake and commit to improvement",
            nextScenarioKey: "se_redemption",
            metricsImpact: { "Team Morale": -5, "Product Quality": 5 },
            consequence: "You begin the long process of rebuilding trust.",
          },
          {
            id: "se_blame_game_b",
            text: "Become defensive and consider leaving the company",
            nextScenarioKey: "se_exit",
            metricsImpact: { "Team Morale": -20, "Product Quality": -15 },
            consequence: "Your career at TechCorp comes to an end.",
          },
        ],
      },
      {
        scenarioKey: "se_sprint_success",
        title: "Victory, But at a Cost",
        description: "Your team delivers all three features on time. The company celebrates the achievement, but several team members are considering leaving due to burnout.",
        stageNumber: 5,
        choices: [
          {
            id: "se_sprint_success_a",
            text: "Advocate for better work-life balance going forward",
            nextScenarioKey: "se_culture_shift",
            metricsImpact: { "Team Morale": 20, "Deadline Progress": -5 },
            consequence: "You help create a healthier team culture.",
          },
          {
            id: "se_sprint_success_b",
            text: "Accept that this is just how startups work",
            nextScenarioKey: "se_startup_grind",
            metricsImpact: { "Deadline Progress": 10, "Team Morale": -10 },
            consequence: "You continue in high-pressure mode, but team turnover increases.",
          },
        ],
      },
      {
        scenarioKey: "se_sustainable_pace",
        title: "Sustainable Success",
        description: "Your team adjusts the timeline and works at a sustainable pace. You deliver the features slightly later than originally planned, but the team is energized and morale is high.",
        stageNumber: 5,
        choices: [
          {
            id: "se_sustainable_pace_a",
            text: "Propose this as the new standard for all future sprints",
            nextScenarioKey: "se_new_standard",
            metricsImpact: { "Team Morale": 25, "Deadline Progress": 5 },
            consequence: "You establish a new, healthier team culture.",
          },
          {
            id: "se_sustainable_pace_b",
            text: "Enjoy the current pace but don't push for permanent change",
            nextScenarioKey: "se_temporary_relief",
            metricsImpact: { "Team Morale": 10, "Deadline Progress": 0 },
            consequence: "The pace may revert to high-pressure in future sprints.",
          },
        ],
      },
      {
        scenarioKey: "se_debt_reduction",
        title: "Technical Excellence",
        description: "Your refactoring efforts significantly reduce technical debt. The codebase becomes easier to work with, and new features are faster to implement.",
        stageNumber: 5,
        choices: [
          {
            id: "se_debt_reduction_a",
            text: "Continue prioritizing technical excellence",
            nextScenarioKey: "se_tech_leader",
            metricsImpact: { "Technical Debt": -20, "Product Quality": 20 },
            consequence: "You become the technical leader of your team.",
          },
          {
            id: "se_debt_reduction_b",
            text: "Shift focus to feature delivery now that the codebase is cleaner",
            nextScenarioKey: "se_feature_acceleration",
            metricsImpact: { "Deadline Progress": 20, "Product Quality": 10 },
            consequence: "You leverage the cleaner codebase to ship features faster.",
          },
        ],
      },
      {
        scenarioKey: "se_feature_priority",
        title: "Balanced Progress",
        description: "Your feature ships on time, and you've made progress on technical debt. The team appreciates your pragmatic approach.",
        stageNumber: 5,
        choices: [
          {
            id: "se_feature_priority_a",
            text: "Continue this balanced approach in future work",
            nextScenarioKey: "se_balanced_leader",
            metricsImpact: { "Product Quality": 15, "Deadline Progress": 15 },
            consequence: "You become known as a pragmatic, effective engineer.",
          },
          {
            id: "se_feature_priority_b",
            text: "Lean more heavily into feature delivery",
            nextScenarioKey: "se_feature_machine",
            metricsImpact: { "Deadline Progress": 25, "Technical Debt": 10 },
            consequence: "You become a prolific feature shipper, but technical debt accumulates.",
          },
        ],
      },
      {
        scenarioKey: "se_optimization",
        title: "Performance Mastery",
        description: "You optimize the dashboard and reduce load times by 60%. Users notice the improvement, and your optimization techniques become a case study for the team.",
        stageNumber: 5,
        choices: [
          {
            id: "se_optimization_a",
            text: "Become the performance expert and mentor others",
            nextScenarioKey: "se_performance_expert",
            metricsImpact: { "Product Quality": 20, "User Satisfaction": 20 },
            consequence: "You become the go-to expert for performance optimization.",
          },
          {
            id: "se_optimization_b",
            text: "Move on to the next feature",
            nextScenarioKey: "se_next_chapter",
            metricsImpact: { "Deadline Progress": 15, "Product Quality": 10 },
            consequence: "You continue building new features with performance in mind.",
          },
        ],
      },
      {
        scenarioKey: "se_accumulation",
        title: "Compounding Issues",
        description: "As you continue shipping features, performance issues accumulate. The codebase becomes harder to maintain, and bugs start appearing more frequently.",
        stageNumber: 5,
        choices: [
          {
            id: "se_accumulation_a",
            text: "Propose a major refactoring to address accumulated issues",
            nextScenarioKey: "se_major_refactor",
            metricsImpact: { "Technical Debt": -25, "Product Quality": 15 },
            consequence: "You finally address the technical debt, but it takes significant time.",
          },
          {
            id: "se_accumulation_b",
            text: "Continue shipping features and accept the technical debt",
            nextScenarioKey: "se_debt_spiral",
            metricsImpact: { "Deadline Progress": 10, "Product Quality": -20 },
            consequence: "Technical debt continues to spiral, making future work harder.",
          },
        ],
      },
      {
        scenarioKey: "se_quality_culture",
        title: "Quality Champion",
        description: "Your commitment to quality inspires the team. Code quality improves across the board, and the team takes pride in their work.",
        stageNumber: 6,
        choices: [
          {
            id: "se_quality_culture_a",
            text: "Propose establishing quality standards for the entire company",
            nextScenarioKey: "se_quality_standards",
            metricsImpact: { "Product Quality": 25, "Team Morale": 15 },
            consequence: "You help establish company-wide quality standards.",
          },
          {
            id: "se_quality_culture_b",
            text: "Focus on maintaining quality within your team",
            nextScenarioKey: "se_team_excellence",
            metricsImpact: { "Product Quality": 20, "Team Morale": 10 },
            consequence: "Your team becomes known for high-quality work.",
          },
        ],
      },
      {
        scenarioKey: "se_balanced_approach",
        title: "The Sweet Spot",
        description: "You find a sustainable balance between quality and speed. Your team delivers features regularly without sacrificing code quality.",
        stageNumber: 6,
        choices: [
          {
            id: "se_balanced_approach_a",
            text: "Document and share your approach with other teams",
            nextScenarioKey: "se_methodology_leader",
            metricsImpact: { "Product Quality": 15, "Team Morale": 15 },
            consequence: "You become a thought leader in sustainable development practices.",
          },
          {
            id: "se_balanced_approach_b",
            text: "Keep your approach within your team",
            nextScenarioKey: "se_team_advantage",
            metricsImpact: { "Product Quality": 10, "Deadline Progress": 10 },
            consequence: "Your team gains a competitive advantage.",
          },
        ],
      },
      {
        scenarioKey: "se_senior_role",
        title: "Leadership Journey Begins",
        description: "You're now a senior engineer leading a team of three junior engineers. You're responsible for mentoring, code quality, and project delivery.",
        stageNumber: 6,
        choices: [
          {
            id: "se_senior_role_a",
            text: "Focus on developing your team members into strong engineers",
            nextScenarioKey: "se_mentor_leader",
            metricsImpact: { "Team Morale": 25, "Product Quality": 15 },
            consequence: "Your team becomes highly skilled and motivated.",
          },
          {
            id: "se_senior_role_b",
            text: "Focus on delivering projects on time and under budget",
            nextScenarioKey: "se_results_leader",
            metricsImpact: { "Deadline Progress": 25, "Team Morale": 5 },
            consequence: "You deliver results, but team development suffers.",
          },
        ],
      },
      {
        scenarioKey: "se_specialist_path",
        title: "Architecture Expert",
        description: "You become the go-to expert for system architecture. You're involved in major design decisions and help shape the company's technical direction.",
        stageNumber: 6,
        choices: [
          {
            id: "se_specialist_path_a",
            text: "Mentor others in architecture and design patterns",
            nextScenarioKey: "se_architect_mentor",
            metricsImpact: { "Product Quality": 25, "Team Morale": 15 },
            consequence: "You build a team of skilled architects.",
          },
          {
            id: "se_specialist_path_b",
            text: "Focus on solving the company's most complex technical challenges",
            nextScenarioKey: "se_problem_solver",
            metricsImpact: { "Product Quality": 30, "Technical Debt": -20 },
            consequence: "You solve critical technical problems and reduce technical debt.",
          },
        ],
      },
      {
        scenarioKey: "se_late_mentorship",
        title: "Better Late Than Never",
        description: "David is happy to mentor you. You start learning more deeply about system design and best practices. Your growth accelerates.",
        stageNumber: 6,
        choices: [
          {
            id: "se_late_mentorship_a",
            text: "Pursue a senior engineer role with David's guidance",
            nextScenarioKey: "se_senior_role",
            metricsImpact: { "Product Quality": 15, "Team Morale": 15 },
            consequence: "You eventually reach senior engineer status.",
          },
          {
            id: "se_late_mentorship_b",
            text: "Explore a specialized technical track",
            nextScenarioKey: "se_specialist_path",
            metricsImpact: { "Product Quality": 20, "Technical Debt": -10 },
            consequence: "You become a specialist in your domain.",
          },
        ],
      },
      {
        scenarioKey: "se_plateau",
        title: "The Plateau",
        description: "After two years, you're still a mid-level engineer. You're productive, but your growth has stalled. You wonder if you should have pursued mentorship earlier.",
        stageNumber: 6,
        choices: [
          {
            id: "se_plateau_a",
            text: "Seek a new role at a different company to reinvigorate your career",
            nextScenarioKey: "se_new_company",
            metricsImpact: { "Product Quality": 5, "Deadline Progress": 5 },
            consequence: "You move to a new company and start fresh.",
          },
          {
            id: "se_plateau_b",
            text: "Finally reach out to David and ask for mentorship",
            nextScenarioKey: "se_late_mentorship",
            metricsImpact: { "Product Quality": 10, "Team Morale": 10 },
            consequence: "You restart your growth journey.",
          },
        ],
      },
      {
        scenarioKey: "se_process_improvement",
        title: "Process Champion",
        description: "Your proposed testing and code review improvements are implemented. The team's code quality improves significantly, and similar issues become rare.",
        stageNumber: 5,
        choices: [
          {
            id: "se_process_improvement_a",
            text: "Expand these processes to other teams",
            nextScenarioKey: "se_company_impact",
            metricsImpact: { "Product Quality": 20, "Team Morale": 10 },
            consequence: "You have a positive impact across the company.",
          },
          {
            id: "se_process_improvement_b",
            text: "Focus on maintaining these processes within your team",
            nextScenarioKey: "se_team_excellence",
            metricsImpact: { "Product Quality": 15, "Team Morale": 10 },
            consequence: "Your team becomes a model for quality.",
          },
        ],
      },
      {
        scenarioKey: "se_cautious_approach",
        title: "Regaining Confidence",
        description: "Your careful approach prevents further issues. Over time, the team's confidence in you gradually returns, though some skepticism remains.",
        stageNumber: 5,
        choices: [
          {
            id: "se_cautious_approach_a",
            text: "Gradually take on more challenging work",
            nextScenarioKey: "se_growth_path",
            metricsImpact: { "Product Quality": 10, "Team Morale": 5 },
            consequence: "You rebuild your reputation and continue growing.",
          },
          {
            id: "se_cautious_approach_b",
            text: "Stick to safer, less complex tasks",
            nextScenarioKey: "se_safe_zone",
            metricsImpact: { "Product Quality": 5, "Deadline Progress": 10 },
            consequence: "You remain productive but in a limited role.",
          },
        ],
      },
      {
        scenarioKey: "se_redemption",
        title: "Redemption Arc",
        description: "You work hard to regain the team's trust. You become more thoughtful in your approach, ask for help when needed, and contribute to improving team processes.",
        stageNumber: 5,
        choices: [
          {
            id: "se_redemption_a",
            text: "Become a champion for better practices",
            nextScenarioKey: "se_process_improvement",
            metricsImpact: { "Product Quality": 15, "Team Morale": 15 },
            consequence: "You turn your mistake into a learning opportunity for the team.",
          },
          {
            id: "se_redemption_b",
            text: "Focus on doing your job well",
            nextScenarioKey: "se_recovery",
            metricsImpact: { "Product Quality": 10, "Team Morale": 10 },
            consequence: "You gradually rebuild trust through consistent performance.",
          },
        ],
      },
      {
        scenarioKey: "se_exit",
        title: "The End",
        description: "You decide to leave TechCorp. While this chapter ends, you take valuable lessons with you about accountability and teamwork.",
        stageNumber: 5,
        choices: [
          {
            id: "se_exit_a",
            text: "Reflect on what you learned and apply it to your next role",
            nextScenarioKey: "se_new_company",
            metricsImpact: { "Product Quality": 0, "Team Morale": 0 },
            consequence: "You move on to a new opportunity.",
          },
        ],
      },
      {
        scenarioKey: "se_culture_shift",
        title: "Healthier Culture",
        description: "Your advocacy leads to policy changes. The company implements flexible hours, remote work options, and realistic deadlines. Team morale improves significantly.",
        stageNumber: 6,
        choices: [
          {
            id: "se_culture_shift_a",
            text: "Continue advocating for employee well-being",
            nextScenarioKey: "se_culture_leader",
            metricsImpact: { "Team Morale": 25, "Product Quality": 10 },
            consequence: "You become a culture leader in the company.",
          },
          {
            id: "se_culture_shift_b",
            text: "Focus on your technical work",
            nextScenarioKey: "se_next_chapter",
            metricsImpact: { "Team Morale": 15, "Product Quality": 10 },
            consequence: "You enjoy the improved culture while focusing on your career.",
          },
        ],
      },
      {
        scenarioKey: "se_startup_grind",
        title: "The Grind Continues",
        description: "You accept the high-pressure culture as part of startup life. You continue shipping features, but you notice team turnover increasing.",
        stageNumber: 6,
        choices: [
          {
            id: "se_startup_grind_a",
            text: "Eventually advocate for change",
            nextScenarioKey: "se_culture_shift",
            metricsImpact: { "Team Morale": 10, "Deadline Progress": -5 },
            consequence: "You realize that sustainable practices are better long-term.",
          },
          {
            id: "se_startup_grind_b",
            text: "Embrace the startup culture and move to a leadership role",
            nextScenarioKey: "se_startup_leader",
            metricsImpact: { "Deadline Progress": 20, "Team Morale": -10 },
            consequence: "You thrive in the high-pressure environment and move up.",
          },
        ],
      },
      {
        scenarioKey: "se_new_standard",
        title: "Company-Wide Impact",
        description: "Your sustainable pace approach becomes the new standard for all teams. The company's productivity and employee satisfaction both improve.",
        stageNumber: 6,
        choices: [
          {
            id: "se_new_standard_a",
            text: "Lead the charge for company-wide process improvements",
            nextScenarioKey: "se_operations_leader",
            metricsImpact: { "Team Morale": 30, "Product Quality": 15 },
            consequence: "You become a leader in operations and culture.",
          },
          {
            id: "se_new_standard_b",
            text: "Continue focusing on your technical work",
            nextScenarioKey: "se_next_chapter",
            metricsImpact: { "Team Morale": 20, "Product Quality": 10 },
            consequence: "You enjoy the benefits of the new culture while advancing technically.",
          },
        ],
      },
      {
        scenarioKey: "se_temporary_relief",
        title: "Back to Reality",
        description: "After a few months, the company returns to high-pressure sprints. You realize that sustainable pace was a temporary relief.",
        stageNumber: 6,
        choices: [
          {
            id: "se_temporary_relief_a",
            text: "Push for permanent change",
            nextScenarioKey: "se_culture_shift",
            metricsImpact: { "Team Morale": 5, "Deadline Progress": -5 },
            consequence: "You advocate for lasting change.",
          },
          {
            id: "se_temporary_relief_b",
            text: "Accept the cycles and adapt",
            nextScenarioKey: "se_startup_grind",
            metricsImpact: { "Deadline Progress": 10, "Team Morale": -5 },
            consequence: "You learn to navigate the ups and downs.",
          },
        ],
      },
      {
        scenarioKey: "se_tech_leader",
        title: "Technical Leadership",
        description: "Your continued focus on technical excellence makes you the technical leader of your team. You're involved in major architecture decisions.",
        stageNumber: 6,
        choices: [
          {
            id: "se_tech_leader_a",
            text: "Expand your influence to the entire engineering organization",
            nextScenarioKey: "se_engineering_leader",
            metricsImpact: { "Product Quality": 25, "Technical Debt": -20 },
            consequence: "You become a senior technical leader.",
          },
          {
            id: "se_tech_leader_b",
            text: "Focus on your team's technical excellence",
            nextScenarioKey: "se_team_excellence",
            metricsImpact: { "Product Quality": 20, "Team Morale": 10 },
            consequence: "Your team becomes known for technical excellence.",
          },
        ],
      },
      {
        scenarioKey: "se_feature_acceleration",
        title: "Rapid Delivery",
        description: "With the cleaner codebase, your team ships features much faster. Productivity increases significantly.",
        stageNumber: 6,
        choices: [
          {
            id: "se_feature_acceleration_a",
            text: "Maintain the balance between speed and quality",
            nextScenarioKey: "se_balanced_leader",
            metricsImpact: { "Deadline Progress": 20, "Product Quality": 15 },
            consequence: "You maintain a healthy balance.",
          },
          {
            id: "se_feature_acceleration_b",
            text: "Push for even faster delivery",
            nextScenarioKey: "se_feature_machine",
            metricsImpact: { "Deadline Progress": 30, "Technical Debt": 15 },
            consequence: "You ship features rapidly, but technical debt starts accumulating again.",
          },
        ],
      },
      {
        scenarioKey: "se_balanced_leader",
        title: "Pragmatic Leader",
        description: "You become known as a pragmatic, effective leader who balances business needs with technical excellence.",
        stageNumber: 6,
        choices: [
          {
            id: "se_balanced_leader_a",
            text: "Pursue a management track",
            nextScenarioKey: "se_manager_track",
            metricsImpact: { "Team Morale": 15, "Deadline Progress": 15 },
            consequence: "You move into management.",
          },
          {
            id: "se_balanced_leader_b",
            text: "Continue as a senior individual contributor",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 15, "Deadline Progress": 15 },
            consequence: "You advance as a senior individual contributor.",
          },
        ],
      },
      {
        scenarioKey: "se_feature_machine",
        title: "The Shipping Machine",
        description: "Your team becomes known for shipping features rapidly. However, technical debt is accumulating, and code quality is declining.",
        stageNumber: 6,
        choices: [
          {
            id: "se_feature_machine_a",
            text: "Pump the brakes and address technical debt",
            nextScenarioKey: "se_major_refactor",
            metricsImpact: { "Technical Debt": -20, "Product Quality": 15 },
            consequence: "You address the technical debt before it becomes critical.",
          },
          {
            id: "se_feature_machine_b",
            text: "Continue shipping features",
            nextScenarioKey: "se_debt_spiral",
            metricsImpact: { "Deadline Progress": 20, "Product Quality": -20 },
            consequence: "Technical debt continues to spiral.",
          },
        ],
      },
      {
        scenarioKey: "se_performance_expert",
        title: "Performance Guru",
        description: "You become the company's performance expert. Your insights help improve the entire product's speed and efficiency.",
        stageNumber: 6,
        choices: [
          {
            id: "se_performance_expert_a",
            text: "Build a performance engineering team",
            nextScenarioKey: "se_performance_team_lead",
            metricsImpact: { "Product Quality": 25, "User Satisfaction": 25 },
            consequence: "You lead a specialized performance team.",
          },
          {
            id: "se_performance_expert_b",
            text: "Continue as an individual contributor",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 20, "User Satisfaction": 20 },
            consequence: "You remain a senior individual contributor focused on performance.",
          },
        ],
      },
      {
        scenarioKey: "se_next_chapter",
        title: "The Next Chapter",
        description: "You've made significant progress in your career at TechCorp. You've shipped features, learned from mistakes, and grown as an engineer.",
        stageNumber: 6,
        choices: [
          {
            id: "se_next_chapter_a",
            text: "Pursue a leadership role at TechCorp",
            nextScenarioKey: "se_manager_track",
            metricsImpact: { "Team Morale": 10, "Deadline Progress": 10 },
            consequence: "You move into leadership.",
          },
          {
            id: "se_next_chapter_b",
            text: "Explore opportunities at other companies",
            nextScenarioKey: "se_new_company",
            metricsImpact: { "Product Quality": 5, "Deadline Progress": 5 },
            consequence: "You start a new chapter at a different company.",
          },
        ],
      },
      {
        scenarioKey: "se_major_refactor",
        title: "The Great Refactoring",
        description: "You embark on a major refactoring effort to address accumulated technical debt. It's a significant undertaking, but the payoff is substantial.",
        stageNumber: 6,
        choices: [
          {
            id: "se_major_refactor_a",
            text: "Lead the refactoring effort",
            nextScenarioKey: "se_tech_leader",
            metricsImpact: { "Technical Debt": -30, "Product Quality": 20 },
            consequence: "You become a technical leader through this effort.",
          },
          {
            id: "se_major_refactor_b",
            text: "Contribute to the refactoring while maintaining feature work",
            nextScenarioKey: "se_balanced_approach",
            metricsImpact: { "Technical Debt": -15, "Product Quality": 10 },
            consequence: "You balance refactoring with feature work.",
          },
        ],
      },
      {
        scenarioKey: "se_debt_spiral",
        title: "The Debt Spiral",
        description: "Technical debt has spiraled out of control. The codebase is difficult to work with, bugs are frequent, and new features take much longer to implement.",
        stageNumber: 6,
        choices: [
          {
            id: "se_debt_spiral_a",
            text: "Advocate for a major refactoring initiative",
            nextScenarioKey: "se_major_refactor",
            metricsImpact: { "Technical Debt": -25, "Product Quality": 10 },
            consequence: "You push for addressing the debt crisis.",
          },
          {
            id: "se_debt_spiral_b",
            text: "Consider leaving for a company with better code quality",
            nextScenarioKey: "se_new_company",
            metricsImpact: { "Product Quality": 0, "Technical Debt": 0 },
            consequence: "You move to a new company.",
          },
        ],
      },
      {
        scenarioKey: "se_quality_standards",
        title: "Company-Wide Quality",
        description: "Your proposed quality standards are adopted across the company. Code quality improves significantly, and the company gains a reputation for high-quality software.",
        stageNumber: 7,
        choices: [
          {
            id: "se_quality_standards_a",
            text: "Lead the quality initiative",
            nextScenarioKey: "se_quality_officer",
            metricsImpact: { "Product Quality": 30, "Team Morale": 15 },
            consequence: "You become the quality champion of the company.",
          },
          {
            id: "se_quality_standards_b",
            text: "Continue your technical work",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 20, "Team Morale": 10 },
            consequence: "You enjoy the benefits of company-wide quality standards.",
          },
        ],
      },
      {
        scenarioKey: "se_team_excellence",
        title: "Team of Excellence",
        description: "Your team becomes known for high-quality work, strong collaboration, and excellent morale. You're a model team within the company.",
        stageNumber: 7,
        choices: [
          {
            id: "se_team_excellence_a",
            text: "Expand your team and replicate the model",
            nextScenarioKey: "se_team_lead",
            metricsImpact: { "Team Morale": 20, "Product Quality": 15 },
            consequence: "You lead a larger team.",
          },
          {
            id: "se_team_excellence_b",
            text: "Keep your team as is and focus on technical excellence",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 20, "Team Morale": 15 },
            consequence: "You maintain a small, excellent team.",
          },
        ],
      },
      {
        scenarioKey: "se_mentor_leader",
        title: "Developer of Talent",
        description: "Your junior engineers grow into strong mid-level engineers under your mentorship. The team's capabilities expand significantly.",
        stageNumber: 7,
        choices: [
          {
            id: "se_mentor_leader_a",
            text: "Expand your team and continue mentoring",
            nextScenarioKey: "se_team_lead",
            metricsImpact: { "Team Morale": 25, "Product Quality": 15 },
            consequence: "You become a team lead known for developing talent.",
          },
          {
            id: "se_mentor_leader_b",
            text: "Move into a formal management role",
            nextScenarioKey: "se_manager_track",
            metricsImpact: { "Team Morale": 20, "Deadline Progress": 10 },
            consequence: "You transition into management.",
          },
        ],
      },
      {
        scenarioKey: "se_results_leader",
        title: "Results-Driven Leader",
        description: "Your team consistently delivers projects on time and under budget. You're known for your ability to execute.",
        stageNumber: 7,
        choices: [
          {
            id: "se_results_leader_a",
            text: "Move into a management role",
            nextScenarioKey: "se_manager_track",
            metricsImpact: { "Deadline Progress": 20, "Team Morale": 5 },
            consequence: "You transition into management.",
          },
          {
            id: "se_results_leader_b",
            text: "Focus on developing your team's skills",
            nextScenarioKey: "se_mentor_leader",
            metricsImpact: { "Team Morale": 15, "Product Quality": 10 },
            consequence: "You balance results with team development.",
          },
        ],
      },
      {
        scenarioKey: "se_architect_mentor",
        title: "Architect and Mentor",
        description: "You mentor a new generation of architects. Your design patterns and principles become the foundation for the company's technical direction.",
        stageNumber: 7,
        choices: [
          {
            id: "se_architect_mentor_a",
            text: "Lead the architecture practice",
            nextScenarioKey: "se_architecture_lead",
            metricsImpact: { "Product Quality": 30, "Team Morale": 15 },
            consequence: "You become the head of architecture.",
          },
          {
            id: "se_architect_mentor_b",
            text: "Continue as a senior architect",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 25, "Team Morale": 10 },
            consequence: "You remain a senior architect.",
          },
        ],
      },
      {
        scenarioKey: "se_problem_solver",
        title: "The Problem Solver",
        description: "You've solved some of the company's most challenging technical problems. Your reputation as a problem-solver is well-established.",
        stageNumber: 7,
        choices: [
          {
            id: "se_problem_solver_a",
            text: "Lead a special projects team",
            nextScenarioKey: "se_special_projects_lead",
            metricsImpact: { "Product Quality": 30, "Technical Debt": -25 },
            consequence: "You lead a team focused on solving critical problems.",
          },
          {
            id: "se_problem_solver_b",
            text: "Continue solving problems as a senior individual contributor",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 25, "Technical Debt": -20 },
            consequence: "You remain a senior problem-solver.",
          },
        ],
      },
      {
        scenarioKey: "se_new_company",
        title: "Fresh Start",
        description: "You've joined a new company with a different culture and technical environment. You bring your experience and continue growing.",
        stageNumber: 7,
        choices: [
          {
            id: "se_new_company_a",
            text: "Apply lessons learned and make an impact",
            nextScenarioKey: "se_impact_maker",
            metricsImpact: { "Product Quality": 10, "Team Morale": 10 },
            consequence: "You make a positive impact at your new company.",
          },
          {
            id: "se_new_company_b",
            text: "Take time to learn the new environment",
            nextScenarioKey: "se_next_chapter",
            metricsImpact: { "Product Quality": 5, "Deadline Progress": 5 },
            consequence: "You settle into your new role.",
          },
        ],
      },
      {
        scenarioKey: "se_company_impact",
        title: "Company-Wide Influence",
        description: "Your process improvements have been adopted across the company. Code quality and team morale have improved significantly.",
        stageNumber: 6,
        choices: [
          {
            id: "se_company_impact_a",
            text: "Lead the quality and process initiatives",
            nextScenarioKey: "se_operations_leader",
            metricsImpact: { "Product Quality": 25, "Team Morale": 20 },
            consequence: "You become a leader in operations.",
          },
          {
            id: "se_company_impact_b",
            text: "Continue your technical work",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 20, "Team Morale": 15 },
            consequence: "You enjoy the benefits of your improvements.",
          },
        ],
      },
      {
        scenarioKey: "se_safe_zone",
        title: "Comfort Zone",
        description: "You've settled into a comfortable role, delivering consistent work without taking on major challenges. Your career has plateaued.",
        stageNumber: 6,
        choices: [
          {
            id: "se_safe_zone_a",
            text: "Challenge yourself to take on more complex work",
            nextScenarioKey: "se_growth_path",
            metricsImpact: { "Product Quality": 10, "Team Morale": 5 },
            consequence: "You push yourself to grow.",
          },
          {
            id: "se_safe_zone_b",
            text: "Accept your current role",
            nextScenarioKey: "se_plateau",
            metricsImpact: { "Product Quality": 0, "Deadline Progress": 0 },
            consequence: "You remain in your comfort zone.",
          },
        ],
      },
      {
        scenarioKey: "se_methodology_leader",
        title: "Thought Leader",
        description: "Your balanced approach to development has become a methodology that other teams are adopting. You're recognized as a thought leader.",
        stageNumber: 7,
        choices: [
          {
            id: "se_methodology_leader_a",
            text: "Formalize your methodology and lead a company-wide initiative",
            nextScenarioKey: "se_operations_leader",
            metricsImpact: { "Product Quality": 25, "Team Morale": 20 },
            consequence: "You become a leader in development practices.",
          },
          {
            id: "se_methodology_leader_b",
            text: "Continue your technical work",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 20, "Team Morale": 15 },
            consequence: "You remain a senior technical contributor.",
          },
        ],
      },
      {
        scenarioKey: "se_team_advantage",
        title: "Competitive Advantage",
        description: "Your team's unique approach gives you a competitive advantage. You deliver high-quality features faster than other teams.",
        stageNumber: 7,
        choices: [
          {
            id: "se_team_advantage_a",
            text: "Lead a larger team",
            nextScenarioKey: "se_team_lead",
            metricsImpact: { "Product Quality": 15, "Deadline Progress": 15 },
            consequence: "You expand your team.",
          },
          {
            id: "se_team_advantage_b",
            text: "Keep your team small and focused",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 15, "Team Morale": 15 },
            consequence: "You maintain your competitive advantage.",
          },
        ],
      },
      {
        scenarioKey: "se_manager_track",
        title: "Management Journey",
        description: "You've transitioned into management. You're now responsible for hiring, performance management, and strategic planning for your team.",
        stageNumber: 7,
        choices: [
          {
            id: "se_manager_track_a",
            text: "Focus on developing your team",
            nextScenarioKey: "se_people_leader",
            metricsImpact: { "Team Morale": 20, "Product Quality": 10 },
            consequence: "You become a people-focused leader.",
          },
          {
            id: "se_manager_track_b",
            text: "Focus on business results",
            nextScenarioKey: "se_results_leader",
            metricsImpact: { "Deadline Progress": 20, "Team Morale": 5 },
            consequence: "You become a results-focused leader.",
          },
        ],
      },
      {
        scenarioKey: "se_engineering_leader",
        title: "Engineering Leadership",
        description: "You've become a leader in the engineering organization. You influence technical decisions across multiple teams.",
        stageNumber: 7,
        choices: [
          {
            id: "se_engineering_leader_a",
            text: "Pursue a VP Engineering role",
            nextScenarioKey: "se_vp_engineering",
            metricsImpact: { "Product Quality": 20, "Team Morale": 15 },
            consequence: "You move into executive leadership.",
          },
          {
            id: "se_engineering_leader_b",
            text: "Remain as a senior technical leader",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 25, "Team Morale": 10 },
            consequence: "You remain a senior technical leader.",
          },
        ],
      },
      {
        scenarioKey: "se_performance_team_lead",
        title: "Performance Engineering Team",
        description: "You've built a specialized team focused on performance optimization. Your team has made significant improvements to the product's speed and efficiency.",
        stageNumber: 7,
        choices: [
          {
            id: "se_performance_team_lead_a",
            text: "Expand the team and make performance a company priority",
            nextScenarioKey: "se_performance_leader",
            metricsImpact: { "Product Quality": 30, "User Satisfaction": 30 },
            consequence: "You become the performance leader.",
          },
          {
            id: "se_performance_team_lead_b",
            text: "Keep the team focused and specialized",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 25, "User Satisfaction": 25 },
            consequence: "You maintain a specialized performance team.",
          },
        ],
      },
      {
        scenarioKey: "se_senior_ic",
        title: "Senior Individual Contributor",
        description: "You've reached the senior individual contributor level. You're a respected expert in your field, contributing significantly to the company's technical direction.",
        stageNumber: 7,
        choices: [
          {
            id: "se_senior_ic_a",
            text: "Transition into management",
            nextScenarioKey: "se_manager_track",
            metricsImpact: { "Team Morale": 10, "Deadline Progress": 10 },
            consequence: "You move into management.",
          },
          {
            id: "se_senior_ic_b",
            text: "Remain as a senior individual contributor",
            nextScenarioKey: "se_end_success",
            metricsImpact: { "Product Quality": 10, "Team Morale": 10 },
            consequence: "You continue as a respected senior contributor.",
          },
        ],
      },
      {
        scenarioKey: "se_impact_maker",
        title: "Making an Impact",
        description: "You've made a positive impact at your new company. You're applying your experience and helping the team improve.",
        stageNumber: 7,
        choices: [
          {
            id: "se_impact_maker_a",
            text: "Pursue a leadership role",
            nextScenarioKey: "se_manager_track",
            metricsImpact: { "Team Morale": 15, "Product Quality": 10 },
            consequence: "You move into leadership.",
          },
          {
            id: "se_impact_maker_b",
            text: "Continue as a senior technical contributor",
            nextScenarioKey: "se_senior_ic",
            metricsImpact: { "Product Quality": 15, "Team Morale": 10 },
            consequence: "You remain a senior technical contributor.",
          },
        ],
      },
      {
        scenarioKey: "se_quality_officer",
        title: "Chief Quality Officer",
        description: "You've become the company's quality champion. You're responsible for maintaining and improving code quality across the organization.",
        stageNumber: 8,
        choices: [
          {
            id: "se_quality_officer_a",
            text: "Continue improving quality standards",
            nextScenarioKey: "se_end_success",
            metricsImpact: { "Product Quality": 30, "Team Morale": 15 },
            consequence: "You continue your mission of quality excellence.",
          },
        ],
      },
      {
        scenarioKey: "se_team_lead",
        title: "Team Lead",
        description: "You're now leading a team of engineers. You're responsible for mentoring, project delivery, and team growth.",
        stageNumber: 8,
        choices: [
          {
            id: "se_team_lead_a",
            text: "Focus on team development",
            nextScenarioKey: "se_people_leader",
            metricsImpact: { "Team Morale": 20, "Product Quality": 10 },
            consequence: "You become a people-focused leader.",
          },
          {
            id: "se_team_lead_b",
            text: "Focus on business results",
            nextScenarioKey: "se_results_leader",
            metricsImpact: { "Deadline Progress": 20, "Team Morale": 5 },
            consequence: "You become a results-focused leader.",
          },
        ],
      },
      {
        scenarioKey: "se_architecture_lead",
        title: "Head of Architecture",
        description: "You're now leading the architecture practice. You're responsible for the company's technical direction and long-term technical strategy.",
        stageNumber: 8,
        choices: [
          {
            id: "se_architecture_lead_a",
            text: "Continue improving the company's architecture",
            nextScenarioKey: "se_end_success",
            metricsImpact: { "Product Quality": 30, "Technical Debt": -25 },
            consequence: "You continue your mission of architectural excellence.",
          },
        ],
      },
      {
        scenarioKey: "se_special_projects_lead",
        title: "Special Projects Lead",
        description: "You're leading a team focused on solving the company's most challenging technical problems.",
        stageNumber: 8,
        choices: [
          {
            id: "se_special_projects_lead_a",
            text: "Continue solving critical problems",
            nextScenarioKey: "se_end_success",
            metricsImpact: { "Product Quality": 30, "Technical Debt": -20 },
            consequence: "You continue your mission of problem-solving.",
          },
        ],
      },
      {
        scenarioKey: "se_culture_leader",
        title: "Culture Champion",
        description: "You've become the company's culture champion. You're leading initiatives to improve employee well-being and team morale.",
        stageNumber: 8,
        choices: [
          {
            id: "se_culture_leader_a",
            text: "Continue building a healthy culture",
            nextScenarioKey: "se_end_success",
            metricsImpact: { "Team Morale": 30, "Product Quality": 10 },
            consequence: "You continue your mission of cultural excellence.",
          },
        ],
      },
      {
        scenarioKey: "se_startup_leader",
        title: "Startup Leader",
        description: "You've embraced the startup culture and moved into a leadership role. You're driving the company's growth and technical direction.",
        stageNumber: 8,
        choices: [
          {
            id: "se_startup_leader_a",
            text: "Continue leading in the startup environment",
            nextScenarioKey: "se_end_success",
            metricsImpact: { "Deadline Progress": 20, "Team Morale": 5 },
            consequence: "You continue your leadership journey.",
          },
        ],
      },
      {
        scenarioKey: "se_operations_leader",
        title: "Operations Leader",
        description: "You're leading operations and process improvements across the company. You're responsible for efficiency, quality, and team well-being.",
        stageNumber: 8,
        choices: [
          {
            id: "se_operations_leader_a",
            text: "Continue improving company operations",
            nextScenarioKey: "se_end_success",
            metricsImpact: { "Product Quality": 25, "Team Morale": 25 },
            consequence: "You continue your mission of operational excellence.",
          },
        ],
      },
      {
        scenarioKey: "se_vp_engineering",
        title: "VP Engineering",
        description: "You've reached the VP Engineering role. You're responsible for the entire engineering organization, including hiring, strategy, and culture.",
        stageNumber: 8,
        choices: [
          {
            id: "se_vp_engineering_a",
            text: "Build a world-class engineering organization",
            nextScenarioKey: "se_end_success",
            metricsImpact: { "Product Quality": 30, "Team Morale": 30 },
            consequence: "You continue building a world-class organization.",
          },
        ],
      },
      {
        scenarioKey: "se_people_leader",
        title: "People Leader",
        description: "You've become known as a people-focused leader. You're excellent at developing talent, building teams, and creating a positive culture.",
        stageNumber: 8,
        choices: [
          {
            id: "se_people_leader_a",
            text: "Continue developing leaders and teams",
            nextScenarioKey: "se_end_success",
            metricsImpact: { "Team Morale": 30, "Product Quality": 15 },
            consequence: "You continue your mission of people development.",
          },
        ],
      },
      {
        scenarioKey: "se_performance_leader",
        title: "Performance Excellence",
        description: "You've made performance a company priority. The product is known for its speed and efficiency.",
        stageNumber: 8,
        choices: [
          {
            id: "se_performance_leader_a",
            text: "Continue improving performance",
            nextScenarioKey: "se_end_success",
            metricsImpact: { "Product Quality": 30, "User Satisfaction": 30 },
            consequence: "You continue your mission of performance excellence.",
          },
        ],
      },
      {
        scenarioKey: "se_end_success",
        title: "Success",
        description: "You've had a successful career at TechCorp. You've grown from a junior engineer to a respected leader or expert. You've made a significant impact on the company and your team.",
        stageNumber: 9,
        choices: [
          {
            id: "se_end_success_a",
            text: "Reflect on your journey",
            nextScenarioKey: "end",
            metricsImpact: {},
            consequence: "Your career at TechCorp has been a success.",
          },
        ],
      },
      {
        scenarioKey: "end",
        title: "The End",
        description: "Your simulation has ended. You've completed your journey through a career in software engineering.",
        stageNumber: 10,
        choices: [],
      },
    ],
  },
};
